esphome:
  name: smallboard
  platform: ESP8266
  board: esp01

wifi:
  ssid: Avalon
  password: raspberry
  power_save_mode: none
  fast_connect: false
  output_power: 20.5db
  ap:
    ssid: "Testroom Fallback Hotspot"
    password: "tsunamis"
    #  manual_ip:  
    #    static_ip: 10.139.10.166
    #    gateway: 10.139.10.1
    #    subnet: 255.255.255.0
    #    dns1: 10.139.10.1

captive_portal:

# Enable logging
logger:
  level: VERBOSE

api:

ota:
