esphome:
  name: testroom
  platform: ESP8266
  board: nodemcu

<<: !include common/config/wifi.yaml
<<: !include common/config/logger.yaml
<<: !include common/config/api.yaml
<<: !include common/config/ota.yaml
<<: !include common/config/time.yaml
<<: !include common/config/web_server.yaml

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Test PIR Sensor"
    device_class: motion

i2c:
  sda: D1
  scl: D2
  scan: True
 
ads1115:
  - address: 0x48

sensor:
  - platform: dht
    pin: D6
    model: DHT11
    temperature:
      name: "Test Room Temperature"
    humidity:
      name: "Test Room Humidity"
    update_interval: 60s
    #  - platform: adc
    #    pin: A0
    #    name: "Multisensor Brightness"
    #    unit_of_measurement: lux
    #    filters:
    #      - lambda: |-
    #          return (x / 10000.0) * 2000000.0;
    # switch:
    #  - platform: gpio
    #    name: "Relay"
    #    pin: D6
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "Multisensor Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
  
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "Multisensor battery percentage"
    unit_of_measurement: percent
    filters:
      - lambda: |-
          return (((x * 5) - 3.3) / 0.9) * 100;
  
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "Multisensor battery voltage"
    unit_of_measurement: volts
    filters:
      - lambda: |-
          return x * 5;
