esphome:
  name: testroom
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: Avalon
  password: raspberry
  power_save_mode: none
  fast_connect: false
  output_power: 20.5db
  ap:
    ssid: "Testroom Fallback Hotspot"
    password: "tsunamis"
    #  manual_ip:  
    #    static_ip: 10.139.10.166
    #    gateway: 10.139.10.1
    #    subnet: 255.255.255.0
    #    dns1: 10.139.10.1

captive_portal:

# Enable logging
logger:
  level: VERBOSE

api:

ota:

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Test PIR Sensor"
    device_class: motion

i2c:
  sda: D1
  scl: D2
  scan: True
 
ads1115:
  - address: 0x48

sensor:
  - platform: dht
    pin: D6
    model: DHT11
    temperature:
      name: "Test Room Temperature"
    humidity:
      name: "Test Room Humidity"
    update_interval: 60s
    #  - platform: adc
    #    pin: A0
    #    name: "Multisensor Brightness"
    #    unit_of_measurement: lux
    #    filters:
    #      - lambda: |-
    #          return (x / 10000.0) * 2000000.0;
    # switch:
    #  - platform: gpio
    #    name: "Relay"
    #    pin: D6
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "Multisensor Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: "Multisensor Gas"
    unit_of_measurement: ppm
    filters:
      - lambda: |-
              return pow((x / 0.00015600) / 37835, -2.752747);
     #      return 1 * 146.15 * (2.868 - x) + 10;
           
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "Multisensor battery percentage"
    unit_of_measurement: percent
    filters:
      - lambda: |-
          return (((x * 5) - 3.3) / 0.9) * 100;
  
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "Multisensor battery voltage"
    unit_of_measurement: volts
    filters:
      - lambda: |-
          return x * 5;
